[mysql]
mysql.devopsadipractice.online

# 172.31.24.119 ansible_user=ec2-user ansible_password=DevOps321

[backend]
backend.devopsadipractice.online

[frontend]
devopsadipractice.online

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321


